
services:
  spotify_auth_proxy:
    build: ./terraform-provider-spotify/spotify_auth_proxy
    ports:
      - "27228:27228"
    env_file:
      - .env

  exporter:
    build:
      context: ./exporter
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
