version: '3.8'
services:
  spotify_auth_proxy:
    build: ./terraform-provider-spotify/spotify_auth_proxy
    ports:
      - "5001:27228"
    env_file:
      - .env
    networks:
      - monitoring

  exporter:
    build:
      context: ./exporter
    ports:
      - "5000:5000"
    env_file:
    - ./exporter/.env
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

networks:
  monitoring: